### PR TITLE
Add functionality to merge existing keys into output files

### PR DESCRIPTION
**Pull request by Rokurolize**
This pull request adds a new feature to the script that handles JSON files. The changes include checking if the output file already exists before writing the processed data. If the output file exists, the script reads the existing data and merges any keys that are not present in the source data. This ensures that the final output file contains both the newly processed data and any previously existing data that does not conflict with the new data.

Also, added `sort_keys=True` when outputting files. Sorted keys make it easier to compare different versions of the file or to identify differences between files.

Example (screenshot from a past PR attempt in the zh_TW repository):
image

EDIT: Below is the Python script used to sort the keys:
```python
import json
import os

def process_json_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)

    with open(file_path, 'w', encoding='utf-8') as file:
        json.dump(data, file, indent=2, ensure_ascii=False, sort_keys=True)

def sort_all_json_files_in_repository(root_dir):
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith('.json'):
                file_path = os.path.join(dirpath, filename)
                process_json_file(file_path)

if __name__ == "__main__":
    repository_path = r'C:\github\stable-diffusion-webui-localization-source'
    sort_all_json_files_in_repository(repository_path)


```

### CODE REVIEW

**Comment by harukaxxxx** [comment]
The original order in JSON is very important due to the way webUI handles translations. Before Automartic1111 optimized the multilingual module, I was powerless to do anything about it.

As far as I understand, when web UI outputs localization.json, it scans the entire DOM once and sequentially puts the contents (beside DOM's structure) into localization.json. This leads to the following problems:

image

In just two short original sentences, web UI splits them into eight keys. If sorting is applied to the keys, it will cause problems finding the context during translation.

Checking for duplicate keys to update values to avoid difficult-to-read diff problems is something I strongly agree with. However, placing new keys at the bottom of the JSON affects the original order. But if the new value is inserted in its original position, it has a similar effect to completely overwriting it. Moreover, deleted text in the extension does not need to be retained in the translation file.

I am well aware that this has caused great difficulties in managing code changes. I currently do not have a better solution, so if you have any other ideas, please let me know. Thank you!

**Comment by Rokurolize** [comment]
Thank you for the detailed explanation!

### Sorting:
Since it is essential to understand the context of the original text to do an accurate translation, I thought it was customary to translate text found on WebUI by searching for it on Crowdin. However, looking at examples like the sample image, certain situations can be difficult. It is a tricky problem.

### Loading Existing Data:
This process aims to protect source texts that only appear in specific contexts. For instance, the source text in the SD body could include the following:
```
{
    "Time taken:": "Time taken:",
    "Waiting...": "Waiting...",
    "behind": "behind",
    "latest": "latest"
}
```
The output template won't include these texts until you check for extension updates. If someone re-exports and replaces the template with a new WebUI version, the keys added by extra work will be lost. That's why I believed it was necessary to validate the existing data.

However, I now realize that creating a separate file is a better approach than merging these keys. This way, we can focus on the necessary keys and disregard outdated text.

**Comment by harukaxxxx** [comment]
> ### Loading Existing Data:
> This process aims to protect source texts that only appear in specific contexts. For instance, the source text in the SD body could include the following:
> 
> ```
> {
>     "Time taken:": "Time taken:",
>     "Waiting...": "Waiting...",
>     "behind": "behind",
>     "latest": "latest"
> }
> ```

I believe this problem should be documented clearly and monitored manually. Until the multilingual module is improved, it cannot be automated.

**Comment by Rokurolize** [comment]
> I believe this problem should be documented clearly and monitored manually. Until the multilingual module is improved, it cannot be automated.

I agree. Let's work out the details on that.

Thank you for the valuable feedback and detailed explanation regarding the pull request. Based on our discussion, I understand that the original order of keys in the JSON file is crucial for context, and sorting the keys might cause translation issues. I also appreciate your input on handling new keys and the importance of manually monitoring source texts that only appear in specific contexts.

Considering the points we've discussed, I will not proceed with the current pull request. Instead, I plan to create an Issue where we can further discuss how to manage special texts.

**Pull request closed without merging**
